build:
	g++ -o main main.cpp -lpthread -Wall -Werror             \
		CommandLineArgumentsParser.cpp SharedVariables.cpp   \
		MapperThread.cpp ReducerThread.cpp                   \
		MapperResult.cpp WordList.cpp
clean:
	rm -f ./main [a-z].txt

