build:
	g++ -o tema1 main.cpp -lpthread -Wall -Werror             \
		CommandLineArgumentsParser.cpp SharedVariables.cpp   \
		MapperThread.cpp ReducerThread.cpp                   \
		MapperResult.cpp WordList.cpp
clean:
	rm -f ./tema1 [a-z].txt

